In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


In [8]:
py_list = [1,2,3]
print("Python list multiplication", py_list*2)
np_array = np.array([1,2,3])
print("Numpy array multiplication", np_array*2)

import time 

start = time.time()
py_list2 = [i*2 for i in range(1000000)]
print("\n List operation time:", time.time() - start)

start2 = time.time()
np_array2 = np.arange(1000000)*2
print("\n Numpy operation time:", time.time() - start2)

Python list multiplication [1, 2, 3, 1, 2, 3]
Numpy array multiplication [2 4 6]

 List operation time: 0.0883185863494873

 Numpy operation time: 0.006964445114135742


In [15]:
zeros = np.zeros((3,4))
print(zeros)
ones = np.ones((3,4))
print(ones)
full = np.full((5,5), 7)
print(full)
random = np.random.random((2,3))
print(random)

sequence = np.arange(0,10, 2)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[0.59810589 0.04200514 0.51840134]
 [0.42762036 0.2123887  0.16640391]]
[0 2 4 6 8]


In [16]:
vector = np.array([1,2,3])
print(vector)

[1 2 3]


In [17]:
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [18]:
tensor = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [21]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
reshaped = arr.reshape((3,4))
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

raveled = reshaped.ravel()
print(raveled)

transpose = reshaped.T
print(transpose)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
