In [1]:
import numpy as np

In [5]:
arr = np.arange(1, 11)
print(arr[2:7])
print(arr[1:8:2])
print(arr[-3])

[3 4 5 6 7]
[2 4 6 8]
8


In [10]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print(arr_2d[1,2])
print(arr_2d[1])
print(arr_2d[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[4 5 6]
[2 5 8]


In [12]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print(np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print(np.sort(arr_2d_unsorted, axis=0))

[1 1 2 3 4 5 6 9]
[[1 1]
 [2 2]
 [3 3]]


In [13]:
numbers = np.arange(1,11)
even_numbers = numbers[numbers%2 == 0]
print(even_numbers)

[ 2  4  6  8 10]


In [14]:
mask = numbers>5
print(numbers[mask])

[ 6  7  8  9 10]


In [15]:
indices = [0,2,4]
print(numbers[indices])

[1 3 5]


In [17]:
where_result =np.where(numbers>5)
print(numbers[where_result])

[ 6  7  8  9 10]


In [21]:
condition_array = np.where(numbers>5, numbers*2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


In [23]:
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)

print(arr1+arr2)
print(np.concatenate((arr1,arr2)))

[5 7 9]
[1 2 3 4 5 6]


In [25]:
a = np.arange(1,4)
b = np.arange(4,7)
c = np.arange(7,10,11)

print(a.shape == b.shape)
print(b.shape == c.shape)

True
False


In [31]:
orignal = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((orignal, new_row))
print(orignal)
print(with_new_row)

new_col = np.array([[9],[0]])
with_new_col = np.hstack((orignal, new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 9]
 [3 4 0]]


In [32]:
arr = np.arange(1,6)
deleted = np.delete(arr, 2)
print(deleted)

[1 2 4 5]
