### NUMPY Basics
### 1. Indexing & Slicing

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [7]:
# Tasks:
# 1. Get first 3 elements
print(arr[:3:])
# 2. Get last 2 elements
print(arr[:-3:-1])
# 3. Reverse the array
print(arr[::-1])

[10 20 30]
[50 40]
[50 40 30 20 10]


### 2. Array Operations

In [14]:
arr = np.array([1, 2, 3, 4])

# Tasks:
# 1. Multiply each element by 2
print(arr * 2)
# 2. Find elements > 2
print(arr > 2)
# 3. Add two arrays
arr_2 = np.array([5,6,7,8])
print(arr + arr_2) #is this right to add this?

[2 4 6 8]
[False False  True  True]
[ 6  8 10 12]


### 3. Shape, Size, ndim

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

# Tasks:
# 1. Find shape
print(arr.shape)
# 2. Find dimensions
print(arr.size)
# 3. Find total elements
# tell me how to this

(2, 3)
6


### 4. Reshpae

In [19]:
arr = np.arange(12)

# Task:
# Convert into 3x4 matrix

arr_new = arr.reshape(3,4)
print(arr_new)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 5. Array Creation

In [25]:
# Tasks:
# 1. Create array from 1 to 10
arr = np.arange(1,11)
print(arr)
# 2. Create 5 evenly spaced numbers between 0 and 1
arr_2 = np.arange(0, 1, 0.2)
print(arr_2)
# 3. Create 3x3 matrix of zeros
print(np.zeros([3,3], dtype=int))

[ 1  2  3  4  5  6  7  8  9 10]
[0.  0.2 0.4 0.6 0.8]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


### 6. Statistical Functions

In [28]:
arr = np.array([10, 20, 30, 40])

# Tasks:
# 1. Find mean
print(np.mean(arr))
# 2. Find standard deviation
print(np.std(arr))
# 3. Find min and max
print(np.min(arr))
print(np.max(arr))

25.0
11.180339887498949
10
40


### 7. Transpose & Ravel

In [36]:
arr = np.array([[1,2,3],[4,5,6]])

# Tasks:
# 1. Transpose matrix
print(np.transpose(arr))
# 2. Convert to 1D array
print(arr.reshape(1,6))

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3 4 5 6]]


### 8. Stacking & Splitting

In [45]:
a = np.array([1,2])
b = np.array([3,4])

# Tasks:
# 1. Stack arrays
print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.stack((a,b)))
# 2. Split array into 2 parts
arr = np.arange(16).reshape(4, 4)
upper, lower = np.vsplit(arr, 2)
print(upper)
print(lower)
left, right = np.hsplit(arr,2)
print(left)
print(right)


[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### 9. Dot Product

In [48]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Task:
# Find dot product
print(a @ b)

32


### 10. Log, Round Functions

In [53]:
arr = np.array([1, 2, 3])

# Tasks:
# 1. Apply log
print(np.log(arr))
# 2. Round values
data = np.array([1.2345, 2.7891, 5.5555])
print(np.round(data, 2))
print(np.floor(data))
print(np.ceil(data))
print(np.trunc(data))

[0.         0.69314718 1.09861229]
[1.23 2.79 5.56]
[1. 2. 5.]
[2. 3. 6.]
[1. 2. 5.]
